spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/modulo09
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
modulo09:
  github-token: 123456
  guse-default-alguma-coisa: true